### ISSUE TITLE
Support configuring number of threads or workers

### ISSUE THREAD

**Issue by sundaraa-deshaw** [warlock-labs/postel#13]
Hi,

Currently, I dont see a way to configure the number of executors or workers in Hyper server.
If I am missing to note, kindly point me to the right doc or source code.
Please let me know if there are plans to add such support.

Arun

**Comment by finnbear** [comment]
It [uses `tokio::spawn`](https://github.com/valorem-labs-inc/hyper-server/blob/6d93b4251766d97120b96ecee6d198b3406da7da/src/server.rs#L247), so threads can be configured using [`tokio::runtime::Builder::worker_threads`](https://docs.rs/tokio/1.39.3/tokio/runtime/struct.Builder.html#method.worker_threads) :ok_hand:

**Comment by 0xAlcibiades** [comment]
Yeah, this is true. Closing accordingly.
